### ISSUE TITLE
Crash assertion failed: range.start % atom_size == 0

### ISSUE THREAD

**Issue by hakolao** [hakolao/egui_winit_vulkano#29]
All examples crash on mac 
```
thread 'main' panicked at 'assertion failed: range.start % atom_size == 0 &&\n    (range.end % atom_size == 0 || range.end == self.size)', /Users/okkohakola/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.32.0/src/memory/allocator/suballocator.rs:312:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/f8588549c3c3d45c32b404210cada01e2a45def3/library/core/src/panicking.rs:48:5
   3: vulkano::memory::allocator::suballocator::MemoryAlloc::create_memory_range
   4: vulkano::buffer::cpu_pool::CpuBufferPool<T,A>::try_next_impl
   5: vulkano::buffer::cpu_pool::CpuBufferPool<T,A>::from_iter
   6: egui_winit_vulkano::renderer::Renderer::draw_egui
   7: egui_winit_vulkano::renderer::Renderer::draw_on_subpass_image
   8: egui_winit_vulkano::integration::Gui::draw_on_subpass_image
   9: subpass::SimpleGuiPipeline::render
  10: subpass::main::{{closure}}
  11: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
  12: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
  13: winit::platform_impl::platform::app_state::AppState::cleared
```

**Comment by hakolao** [comment]
Seems to occur on vulkano example too
